services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_URL=http://backend:5001/greet
    depends_on:
      - backend